//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FameBot {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class _RealmQuests : global::System.Configuration.ApplicationSettingsBase {
        
        private static _RealmQuests defaultInstance = ((_RealmQuests)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new _RealmQuests())));
        
        public static _RealmQuests Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int _MinStarsToCluster {
            get {
                return ((int)(this["_MinStarsToCluster"]));
            }
            set {
                this["_MinStarsToCluster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NexusRealmClosedDelay {
            get {
                return ((int)(this["NexusRealmClosedDelay"]));
            }
            set {
                this["NexusRealmClosedDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IgnoreLich {
            get {
                return ((bool)(this["IgnoreLich"]));
            }
            set {
                this["IgnoreLich"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IgnoreGhostKing {
            get {
                return ((bool)(this["IgnoreGhostKing"]));
            }
            set {
                this["IgnoreGhostKing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100000")]
        public int TeleportToSentryHealth {
            get {
                return ((int)(this["TeleportToSentryHealth"]));
            }
            set {
                this["TeleportToSentryHealth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IgnoreAvatar {
            get {
                return ((bool)(this["IgnoreAvatar"]));
            }
            set {
                this["IgnoreAvatar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MoveToBlueBags {
            get {
                return ((bool)(this["MoveToBlueBags"]));
            }
            set {
                this["MoveToBlueBags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int _ClusterRadius {
            get {
                return ((int)(this["_ClusterRadius"]));
            }
            set {
                this["_ClusterRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IgnoreEnt {
            get {
                return ((bool)(this["IgnoreEnt"]));
            }
            set {
                this["IgnoreEnt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IgnorePentaract {
            get {
                return ((bool)(this["IgnorePentaract"]));
            }
            set {
                this["IgnorePentaract"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IgnoreCube {
            get {
                return ((bool)(this["IgnoreCube"]));
            }
            set {
                this["IgnoreCube"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IgnoreSentry {
            get {
                return ((bool)(this["IgnoreSentry"]));
            }
            set {
                this["IgnoreSentry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IgnoreStatues {
            get {
                return ((bool)(this["IgnoreStatues"]));
            }
            set {
                this["IgnoreStatues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MoveToBagDelay {
            get {
                return ((int)(this["MoveToBagDelay"]));
            }
            set {
                this["MoveToBagDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int _ClusterRadiusPentaract {
            get {
                return ((int)(this["_ClusterRadiusPentaract"]));
            }
            set {
                this["_ClusterRadiusPentaract"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TeleportAwayDelay {
            get {
                return ((int)(this["TeleportAwayDelay"]));
            }
            set {
                this["TeleportAwayDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TeleportToBag {
            get {
                return ((bool)(this["TeleportToBag"]));
            }
            set {
                this["TeleportToBag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int _ClusterRadiusSentry {
            get {
                return ((int)(this["_ClusterRadiusSentry"]));
            }
            set {
                this["_ClusterRadiusSentry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NexusReskin {
            get {
                return ((bool)(this["NexusReskin"]));
            }
            set {
                this["NexusReskin"] = value;
            }
        }
    }
}
