//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mila {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class MilaConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static MilaConfig defaultInstance = ((MilaConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MilaConfig())));
        
        public static MilaConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlockSpam {
            get {
                return ((bool)(this["BlockSpam"]));
            }
            set {
                this["BlockSpam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogGuildChat {
            get {
                return ((bool)(this["LogGuildChat"]));
            }
            set {
                this["LogGuildChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogPrivateMessages {
            get {
                return ((bool)(this["LogPrivateMessages"]));
            }
            set {
                this["LogPrivateMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NotifyVialPickup {
            get {
                return ((bool)(this["NotifyVialPickup"]));
            }
            set {
                this["NotifyVialPickup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AntiLag {
            get {
                return ((bool)(this["AntiLag"]));
            }
            set {
                this["AntiLag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CommandGuard {
            get {
                return ((bool)(this["CommandGuard"]));
            }
            set {
                this["CommandGuard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlockChat {
            get {
                return ((bool)(this["BlockChat"]));
            }
            set {
                this["BlockChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlockGuildInvites {
            get {
                return ((bool)(this["BlockGuildInvites"]));
            }
            set {
                this["BlockGuildInvites"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlockPrivateMessages {
            get {
                return ((bool)(this["BlockPrivateMessages"]));
            }
            set {
                this["BlockPrivateMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LogChat {
            get {
                return ((bool)(this["LogChat"]));
            }
            set {
                this["LogChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SpellRandomColor {
            get {
                return ((bool)(this["SpellRandomColor"]));
            }
            set {
                this["SpellRandomColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlockTradeRequests {
            get {
                return ((bool)(this["BlockTradeRequests"]));
            }
            set {
                this["BlockTradeRequests"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int NotifyNexusPlayerWave {
            get {
                return ((int)(this["NotifyNexusPlayerWave"]));
            }
            set {
                this["NotifyNexusPlayerWave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("450")]
        public int NotifyLag {
            get {
                return ((int)(this["NotifyLag"]));
            }
            set {
                this["NotifyLag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool zDebug {
            get {
                return ((bool)(this["zDebug"]));
            }
            set {
                this["zDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ResizePlayers {
            get {
                return ((int)(this["ResizePlayers"]));
            }
            set {
                this["ResizePlayers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReplaceQuestWithSentry {
            get {
                return ((bool)(this["ReplaceQuestWithSentry"]));
            }
            set {
                this["ReplaceQuestWithSentry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NexusPause {
            get {
                return ((bool)(this["NexusPause"]));
            }
            set {
                this["NexusPause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RedGlow {
            get {
                return ((bool)(this["RedGlow"]));
            }
            set {
                this["RedGlow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayerLeftNotify {
            get {
                return ((bool)(this["PlayerLeftNotify"]));
            }
            set {
                this["PlayerLeftNotify"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GuildNameToServerName {
            get {
                return ((bool)(this["GuildNameToServerName"]));
            }
            set {
                this["GuildNameToServerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Beg {
            get {
                return ((string)(this["Beg"]));
            }
            set {
                this["Beg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BegToggle {
            get {
                return ((bool)(this["BegToggle"]));
            }
            set {
                this["BegToggle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UnblockEveryone {
            get {
                return ((bool)(this["UnblockEveryone"]));
            }
            set {
                this["UnblockEveryone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotifyEggBag {
            get {
                return ((bool)(this["NotifyEggBag"]));
            }
            set {
                this["NotifyEggBag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotifyBlueBag {
            get {
                return ((bool)(this["NotifyBlueBag"]));
            }
            set {
                this["NotifyBlueBag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string USW2_Sell_Msg {
            get {
                return ((string)(this["USW2_Sell_Msg"]));
            }
            set {
                this["USW2_Sell_Msg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NotifyWhiteBag {
            get {
                return ((bool)(this["NotifyWhiteBag"]));
            }
            set {
                this["NotifyWhiteBag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoUseCloverAndLootDrop {
            get {
                return ((bool)(this["AutoUseCloverAndLootDrop"]));
            }
            set {
                this["AutoUseCloverAndLootDrop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool USW2_Sell {
            get {
                return ((bool)(this["USW2_Sell"]));
            }
            set {
                this["USW2_Sell"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotifyRealmQuests {
            get {
                return ((bool)(this["NotifyRealmQuests"]));
            }
            set {
                this["NotifyRealmQuests"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlockGuildChat {
            get {
                return ((bool)(this["BlockGuildChat"]));
            }
            set {
                this["BlockGuildChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("def")]
        public string USW2_Filter_Msg1 {
            get {
                return ((string)(this["USW2_Filter_Msg1"]));
            }
            set {
                this["USW2_Filter_Msg1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("def")]
        public string USW2_Filter_Msg2 {
            get {
                return ((string)(this["USW2_Filter_Msg2"]));
            }
            set {
                this["USW2_Filter_Msg2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("def")]
        public string USW2_Filter_Msg3 {
            get {
                return ((string)(this["USW2_Filter_Msg3"]));
            }
            set {
                this["USW2_Filter_Msg3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool USW2_Filter_Msg {
            get {
                return ((bool)(this["USW2_Filter_Msg"]));
            }
            set {
                this["USW2_Filter_Msg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UnlockEveryone {
            get {
                return ((bool)(this["UnlockEveryone"]));
            }
            set {
                this["UnlockEveryone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("68")]
        public int ShowGuildless {
            get {
                return ((int)(this["ShowGuildless"]));
            }
            set {
                this["ShowGuildless"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PopMysteryStatPots {
            get {
                return ((bool)(this["PopMysteryStatPots"]));
            }
            set {
                this["PopMysteryStatPots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FillMiddleVault {
            get {
                return ((bool)(this["FillMiddleVault"]));
            }
            set {
                this["FillMiddleVault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotifyOrangeBag {
            get {
                return ((bool)(this["NotifyOrangeBag"]));
            }
            set {
                this["NotifyOrangeBag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotifyRedBag {
            get {
                return ((bool)(this["NotifyRedBag"]));
            }
            set {
                this["NotifyRedBag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StackTokens {
            get {
                return ((bool)(this["StackTokens"]));
            }
            set {
                this["StackTokens"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LockGuildies {
            get {
                return ((bool)(this["LockGuildies"]));
            }
            set {
                this["LockGuildies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoRespondToMessages {
            get {
                return ((bool)(this["AutoRespondToMessages"]));
            }
            set {
                this["AutoRespondToMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AutoRespondToMessagesMsg {
            get {
                return ((string)(this["AutoRespondToMessagesMsg"]));
            }
            set {
                this["AutoRespondToMessagesMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public int AutoRespondToMessagesAfter {
            get {
                return ((int)(this["AutoRespondToMessagesAfter"]));
            }
            set {
                this["AutoRespondToMessagesAfter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VaultSpawnCloseToVault {
            get {
                return ((bool)(this["VaultSpawnCloseToVault"]));
            }
            set {
                this["VaultSpawnCloseToVault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teeeheee")]
        public string HS_Map {
            get {
                return ((string)(this["HS_Map"]));
            }
            set {
                this["HS_Map"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HS_CharID {
            get {
                return ((int)(this["HS_CharID"]));
            }
            set {
                this["HS_CharID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HS_Normal {
            get {
                return ((int)(this["HS_Normal"]));
            }
            set {
                this["HS_Normal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HS_Enabled {
            get {
                return ((bool)(this["HS_Enabled"]));
            }
            set {
                this["HS_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teeeheee")]
        public string HS_PrevMap {
            get {
                return ((string)(this["HS_PrevMap"]));
            }
            set {
                this["HS_PrevMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HS_Delay {
            get {
                return ((int)(this["HS_Delay"]));
            }
            set {
                this["HS_Delay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teeeheee")]
        public string HS_PrevMap2 {
            get {
                return ((string)(this["HS_PrevMap2"]));
            }
            set {
                this["HS_PrevMap2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HS_Delayed {
            get {
                return ((bool)(this["HS_Delayed"]));
            }
            set {
                this["HS_Delayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teeeheee")]
        public string HS_PrevMap3 {
            get {
                return ((string)(this["HS_PrevMap3"]));
            }
            set {
                this["HS_PrevMap3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teeeheee")]
        public string HS_Map2 {
            get {
                return ((string)(this["HS_Map2"]));
            }
            set {
                this["HS_Map2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teeeheee")]
        public string HS_Map3 {
            get {
                return ((string)(this["HS_Map3"]));
            }
            set {
                this["HS_Map3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teeeheee")]
        public string HS_Map4 {
            get {
                return ((string)(this["HS_Map4"]));
            }
            set {
                this["HS_Map4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teeeheee")]
        public string HS_Map5 {
            get {
                return ((string)(this["HS_Map5"]));
            }
            set {
                this["HS_Map5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Name {
            get {
                return ((string)(this["Name"]));
            }
            set {
                this["Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("76")]
        public int Stars {
            get {
                return ((int)(this["Stars"]));
            }
            set {
                this["Stars"] = value;
            }
        }
    }
}
