//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib_K_Relay {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    public sealed partial class StealthConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static StealthConfig defaultInstance = ((StealthConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new StealthConfig())));
        
        public static StealthConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StealthEnabled {
            get {
                return ((bool)(this["StealthEnabled"]));
            }
            set {
                this["StealthEnabled"] = value;
            }
        }
    }
}
